// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrs5ZoPHHu-Wi3S0RpJ7FtpsKRe8J3O9A',
    appId: '1:587250190483:web:3f44e2ade01d0e53766566',
    messagingSenderId: '587250190483',
    projectId: 'ionic-test-315f4',
    authDomain: 'ionic-test-315f4.firebaseapp.com',
    storageBucket: 'ionic-test-315f4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtFrFx622xyPvqM9oDdWy3N7P-iHfMF6w',
    appId: '1:263610497489:android:34b48554918c6510c908f0',
    messagingSenderId: '263610497489',
    projectId: 'lonelybyetrip',
    storageBucket: 'lonelybyetrip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTxz0NC9CzcsglvJ2ZTyx6ZaSrRlZMAGw',
    appId: '1:587250190483:ios:f8b4794dcf5da16b766566',
    messagingSenderId: '587250190483',
    projectId: 'ionic-test-315f4',
    storageBucket: 'ionic-test-315f4.appspot.com',
    iosClientId:
        '587250190483-erirh2pkih56tcpcrn0dp1a6gcdfc0uo.apps.googleusercontent.com',
    iosBundleId: 'com.moon.historycollection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTxz0NC9CzcsglvJ2ZTyx6ZaSrRlZMAGw',
    appId: '1:587250190483:ios:6d7bf4dfa8b9d9ed766566',
    messagingSenderId: '587250190483',
    projectId: 'ionic-test-315f4',
    storageBucket: 'ionic-test-315f4.appspot.com',
    iosClientId:
        '587250190483-31qkl76eem4e1km1lckb2eslb2b3ifth.apps.googleusercontent.com',
    iosBundleId: 'com.moon.historycollection',
  );
}
